### ISSUE TITLE
主程序第58行代码错误

### ISSUE THREAD

**Issue by meng-luo** [NanoNM/pythonProject#2]
倒是不影响运行
![Snipaste_2021-09-04_20-01-34](https://user-images.githubusercontent.com/79274361/132093732-6ba5d48e-4315-4b38-8864-960d0e9380c0.png)

**Comment by NanoNM** [comment]
我用了is代替==了

从 python 3.8 开始，使用 is 和 is not 运算符时，会抛出 SyntaxWarning 语句警告信息
